### ISSUE TITLE
Colab Notebook is broken

### ISSUE THREAD

**Issue by hagenkaiser** [fenneishi/Fooocus-Control#33]
when using Colab Notebook it tries to cd into /content/Fooocus which obviously does not exist as the git clone creates a directory called Fooocus-Control instead.
If one fixes this manually the next error is Module "einops" not found. 
This is where Im stuck then

**Comment by xale76** [comment]
me too, did they come back to you with any solution?

**Comment by sitzbrau** [comment]
> when using Colab Notebook it tries to cd into /content/Fooocus which obviously does not exist as the git clone creates a directory called Fooocus-Control instead. If one fixes this manually the next error is Module "einops" not found. This is where Im stuck then

fixed with

`!pip3 install --force einops==0.4.1`

**Comment by SkelegonDK** [comment]
I added einops but I still get this other error. 
The interface in gradio works, but the models are not being loaded and it gets stuck on initialize. 
```Keyboard interruption in main thread... closing server.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2133, in block_thread
    time.sleep(0.1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Fooocus-Control/entry_with_update.py", line 47, in <module>
    from launch import *
  File "/content/Fooocus-Control/launch.py", line 88, in <module>
    from webui import *
  File "/content/Fooocus-Control/webui.py", line 359, in <module>
    shared.gradio_root.launch(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2049, in launch
    self.block_thread()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2137, in block_thread
    self.server.close()
  File "/usr/local/lib/python3.10/dist-packages/gradio/networking.py", line 49, in close
    self.thread.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
Killing tunnel 127.0.0.1:7860 <> https://64471bfcc2e7e9d2e8.gradio.live/
```
colab
```
!pip install pygit2==1.12.2
!pip install einops  # Added line to install einops
%cd /content
!git clone https://github.com/fenneishi/Fooocus-Control.git
%cd /content/Fooocus-Control
```

**Comment by briziomusic** [comment]
> > when using Colab Notebook it tries to cd into /content/Fooocus which obviously does not exist as the git clone creates a directory called Fooocus-Control instead. If one fixes this manually the next error is Module "einops" not found. This is where Im stuck then
> 
> fixed with
> 
> `!pip3 install --force einops==0.4.1`

Hello, could you please share a working colab file or rows?
I'm not able to run it in google colab.
Thanks

**Comment by DiCeYMaYo** [comment]
did anyone find a working Colab notebook?
